// <auto-generated />
using BailamMVC.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BailamMVC.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250715111500_InitDatabase")]
    partial class InitDatabase
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.6");

            modelBuilder.Entity("BailamMVC.Models.Entities.DaiLy", b =>
                {
                    b.Property<string>("MaDaiLy")
                        .HasColumnType("TEXT");

                    b.Property<string>("DiaChi")
                        .HasColumnType("TEXT");

                    b.Property<string>("DienThoai")
                        .HasColumnType("TEXT");

                    b.Property<string>("HeThongPhanPhoiMaHTTP")
                        .HasColumnType("TEXT");

                    b.Property<string>("MaHTTP")
                        .HasColumnType("TEXT");

                    b.Property<string>("NguoiDaiDien")
                        .HasColumnType("TEXT");

                    b.Property<string>("TenDaiLy")
                        .HasColumnType("TEXT");

                    b.HasKey("MaDaiLy");

                    b.HasIndex("HeThongPhanPhoiMaHTTP");

                    b.ToTable("DaiLy");
                });

            modelBuilder.Entity("BailamMVC.Models.Entities.Employee", b =>
                {
                    b.Property<string>("EmployeeId")
                        .HasColumnType("TEXT");

                    b.Property<int>("Age")
                        .HasColumnType("INTEGER");

                    b.HasKey("EmployeeId");

                    b.ToTable("Employee");
                });

            modelBuilder.Entity("BailamMVC.Models.Entities.HeThongPhanPhoi.HeThongPhanPhoi", b =>
                {
                    b.Property<string>("MaHTTP")
                        .HasColumnType("TEXT");

                    b.Property<string>("TenHTPP")
                        .HasColumnType("TEXT");

                    b.HasKey("MaHTTP");

                    b.ToTable("HeThongPhanPhoi");
                });

            modelBuilder.Entity("BailamMVC.Models.Entities.Person", b =>
                {
                    b.Property<string>("PersonId")
                        .HasColumnType("TEXT");

                    b.Property<string>("AddRess")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Height")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("PersonId");

                    b.ToTable("Person");
                });

            modelBuilder.Entity("BailamMVC.Models.Entities.DaiLy", b =>
                {
                    b.HasOne("BailamMVC.Models.Entities.HeThongPhanPhoi.HeThongPhanPhoi", null)
                        .WithMany("DaiLy")
                        .HasForeignKey("HeThongPhanPhoiMaHTTP");
                });

            modelBuilder.Entity("BailamMVC.Models.Entities.HeThongPhanPhoi.HeThongPhanPhoi", b =>
                {
                    b.Navigation("DaiLy");
                });
#pragma warning restore 612, 618
        }
    }
}
